from __future__ import annotations

import re


# These identifiers are clearer in their original form.  URLs are protected
# separately so terminology replacements can never damage a link.
PROTECTED_TERMS = (
    "Craft of the Titans",
    "Craft Of The Titans",
    "Craft of Titans",
    "Craft Of Titans",
    "Better Questing",
    "Ender IO",
    "EnderIO",
    "IndustrialCraft 2",
    "Industrial Craft 2",
    "Industrial Craft",
    "Ars Magica 2",
    "Ars Magicka 2",
    "Ars Magica",
    "Ars Magicka",
    "AbyssalCraft",
    "RFTools",
    "MineFactory",
    "Mob Grinding Utils",
    "ArmorPlus",
    "IC2",
    "EU",
    "Bosses",
    "Boss",
    "JEI",
    "NEI",
    "GUI",
    "RF/t",
    "RF",
    "GP",
    "LP",
    "LE",
    "XP",
    "AM2",
    "BSU",
    "OSS",
)


TITLE_TRANSLATIONS = {
    "New Location": "新地點",
    "The Beneath": "地底世界",
    "The Nether": "地獄",
    "Y Level 40": "Y 高度 40",
    "Enter The Aether": "進入天域",
    'Gas Turbine Generator': '燃氣渦輪發電機',
    'The Best A Man Can Get': '男人的最佳選擇',
    "Uncommon Rune": "罕見符文",
    "Put That Vat To Use!": "把那個發酵桶用起來！",
    "It's Not Called Vein Miner!": "它才不叫礦脈挖掘！",
    "Such a Sap": "真是棵嫩苗",
    "Viper MKII": "毒蛇 MKII",
    "IC2 Of You": "我看到兩個你（IC2）",
    "Chips Alloy": "合金到貨！",
    "Juicy Fruit": "多汁鮮果",
    "Blade Runner": "銀翼殺手",
    "Casting Call": "鑄造召集令",
    "Just In Case": "以防萬一",
    "Gas Turbine": "燃氣渦輪機",
    "Pass The Gas": "把燃氣傳過來",
    "What a Creep": "真是個苦力怕",
    "I am Grout.": "我是泥漿。",
    "Withe Or Not": "凋零與否",
    "Wither Or Not": "凋零與否",
    "Tinker's I/O": "匠魂 I/O",
    "Gravity Falls": "重力墜落",
    "Cobble Gobble": "狼吞鵝卵石",
    "Richie Ritual": "儀式富翁",
    "Dirty Drawers": "髒兮兮的抽屜",
    "Meet Joe Hack": "認識砍殺喬",
    "Balls of Steel": "鋼鐵之球",
    "Copper Stopper": "銅製煞車",
    "Writers Block": "寫作者的方塊",
    "Feed The Beast": "餵養野獸",
    "Im Your #1 Fan": "我是你的頭號風扇",
    "I Know Kung Fu": "我會功夫",
    "Up Up And Away": "向上、向上、起飛！",
    "Rare Titan Run": "稀有泰坦符文",
    "You Con-du-it!": "導管就交給你！",
    "Lead By Example": "以鉛作則",
    "Power Capacitor": "能量電容器",
    "Water Way To Go": "水到渠成",
    "I Wish You Wood": "祝你有木材",
    "Alloy Meets Girl": "合金邂逅女孩",
    "Food For Thought": "精神食糧",
    "Making Ends Meet": "接通兩端",
    "Roomba Schmoomba": "掃地機器人算什麼",
    "Meteor For Meat": "肉品隕石",
    "Treated Unfairly": "防腐木也受不公平待遇",
    "Drawersassination": "抽屜暗殺",
    "Home On The Range": "牧場上的家",
    "Hit the Road Jack": "上路吧，傑克",
    "Let Me Upgrade Ya": "讓我替你升級",
    "Time To Upgrade Ya": "是時候升級了",
    "Trashcan Smashcan": "垃圾桶粉碎桶",
    "24k And Lots Of It": "24K，滿滿都是",
    "Alloy There Matey!": "合金你好啊，夥伴！",
    "Alloy There Maytee!": "合金你好啊，夥伴！",
    "Ars Kickin Magicka": "Ars Magicka 大顯神威",
    "He Who Smelt it...": "誰聞到，誰冶煉……",
    "I Like To Watch...": "我喜歡旁觀……",
    "Lucky Block Buster": "幸運方塊剋星",
    "The Final Frontier": "最後疆界",
    "Sag Millionaire": "SAG 百萬富翁",
    "Alchemy Array Relay": "煉金法陣接力",
    "Valkyrie Vengeance": "女武神復仇",
    "Better With Baubles": "有飾品更好",
    "Expanding Thermally": "熱力膨脹",
    "Great Balls of Fire": "烈焰巨球",
    "Dynamo or Dynaless?": "有發電機，還是沒發電機？",
    "Regeneration Nation": "回復之國",
    "Gettin Wood, Indeed": "確實拿到木頭了",
    "Mekfarming For Meat": "MekFarm 肉品農場",
    "Its An Animal House": "這是動物之家",
    "Somebunny Loves You": "有隻兔兔愛著你",
    "Formal Metal Forming": "正式金屬成型",
    "He Went To Jareds...": "他去了 Jared 珠寶店……",
    "Ritual: Storage Star": "儀式：儲存之星",
    "Respek Mah Athoritae": "尊重我的權威！",
    "Whos In Charge Here?": "誰負責充電？",
    "Sunnarium In My Eyes": "眼中盡是陽光化合物",
    "I Believe You Can Fly": "我相信你能飛",
    "Like A Bat Outta Hell": "如蝙蝠逃出地獄",
    "Finish Your Sentients": "完成你的感知武器",
    "Induction To Industry": "工業感應入門",
    "More Balls Than Eight": "球可不只八顆",
    "The Brahemic Exchange": "Brahemic 交易所",
    "Welcome To The Jungle": "歡迎來到叢林",
    "Out of the Wood Works": "木工作品出爐",
    "More Like Never Stars": "這才叫永不之星",
    "I'm a Big Fan Of Yours": "我是你的大風扇",
    "Do You Mind If I Bind?": "介意我綁定嗎？",
    "Interface is The Place": "介面就是關鍵",
    "Im On Top Of The World": "世界之巔",
    "Iron Out Your Problems": "用鐵解決問題",
    "The Canner Do Atittude": "裝罐機的積極態度",
    "Water Wheel Of Fortune": "幸運水車",
    "Robin Hood If He Could": "羅賓漢也辦不到",
    "Tanks For All The Help": "謝謝儲槽幫忙",
    "Ol McDonald Had a Farm": "老麥克唐納有座農場",
    "Whats In Store For You": "為你儲存了什麼？",
    "Flight Of The Navigator": "領航員之旅",
    "Flight Of The Navigator II": "領航員之旅 II",
    "Im In Love Wit The Coke": "愛上焦煤",
    "Im In Love Wit the Coke Oven": "愛上焦煤爐",
    "Here's My Counter Offer": "這是我的流理臺還價",
    "I Can Fly Twice As High": "我能飛得高一倍",
    "Where There's a Will...": "有意志就有辦法……",
    "Canola Come Out To Play?": "芥花籽，出來玩嗎？",
    "EU Aint Just a Continent": "EU 不只是歐盟",
    "Into The Abyss and Above": "上窮碧落下深淵",
    "Fly Higher Than An Eagle": "飛得比鷹更高",
    "Mass Fabulous Fabricator": "華麗的物質製造機",
    "Frying Pan Into The Fire": "跳出煎鍋，掉進火裡",
    "More Like Instant Output": "這才叫即時輸出",
    "Silver Tidings My Friend": "銀光佳音，我的朋友",
    "Silver Tiding My Friends": "銀光佳音，我的朋友",
    "Slice, Splice, and Bind?": "切片、接合與綁定",
    "The Motion Of The Potion": "藥水的律動",
    "Hell To The Ya Fire Forge": "獄火鍛爐，讚啦！",
    "Mobs Drop It Like Its Hot": "生物掉落正火熱",
    "It's a Bird' Its a Plane!": "是鳥？是飛機！",
    "They Did The Monster Mash": "怪物大混戰",
    "Powerstone Tracker Hacker": "能量石追蹤器駭客",
    "Actually All The Additions": "實用拓展，全都要",
    "Pam Is Back On The Market": "Pam 重返市場",
    "Solar?! I barely know her!": "太陽能？我跟她不熟！",
    "Ol McDonald Grew Some Harm": "老麥克唐納種出了傷害",
    "Blaster? I barely know her!": "爆破器？我跟她不熟！",
    "You Are Gonna Have a Blast": "炸個痛快",
    "Who Framed Amelia Aerhart?": "誰框住了愛蜜莉亞・艾爾哈特？",
    "Pepper Pots and Peter Pans": "胡椒罐與平底鍋",
    "Drawer Control To Major Tom": "抽屜控制器呼叫湯姆少校",
    "Its Time To Bite The Bullet": "是時候咬緊子彈",
    "The Sunnarium Will Come Out": "陽光化合物終會升起",
    "What Core Could You Ask For": "核心還能要求什麼？",
    "By Forge, I Tink He's Got It": "以鍛造之名，我想他懂了",
    "Follow or Subscriber Options": "追蹤或訂閱選項",
    "Collossal Chests Be the Best": "巨型儲物箱最棒",
    "Spawner?  I barely know her!": "生怪磚？我跟她不熟！",
    "Prescription for Inscription": "銘文處方",
    "Butcher?!  I barely know her!": "屠夫？我跟她不熟！",
    "Agricultural Asteroid Reagent": "農業小行星試劑",
    "Mystical Agriculturel You Say": "你說神秘農業？",
    "Compressing The Right Buttons": "按對壓縮按鈕",
    "Shake What Your Mama Gave Ya": "搖動老媽給你的本錢",
    "Sheepuff?  I barely know her!": "Sheepuff？我跟她不熟！",
    "Never Bring Sand To the Beach": "別帶沙子去海灘",
    "Extreme Crafting At Its Finest": "終極合成的極致",
    "The Windmill Beneath My Wings": "翼下的風車",
    "Over Reacting Is a Good Thing": "反應過度才是好事",
    "Aum... are you gonna eat that?": "Aum……你要吃那個嗎？",
    "Gordon Ramstein Would Be Proud": "戈登・羊姆齊會很驕傲",
    "GP, The Other, Other White Meat": "GP，另一種白肉",
    "I Can Can With The Best Of Them": "我最會裝罐",
    "Might Morphin Empowered Ranger": "金剛戰士，賦能變身！",
    "Energy Emitter and Fluid Intake": "能量發射器與流體輸入口",
    "Whether The Wither Will Or Not": "凋零與否",
    "Industrial Craft Of The Titans?": "泰坦工業工藝？",
    "Not The Blade Runner Replicants": "不是《銀翼殺手》的複製人",
    "Metal Former, Robot In Disguise": "金屬成型機，偽裝的機器人",
    "The Ludicrous Cost Of Ludicrite": "鎦方塊的荒唐成本",
    "First The Canner, Now The Scanner": "先是裝罐機，現在是掃描器",
    "Better Than An Anvil, Half The Fat": "勝過鐵砧，脂肪減半",
    "I Guess This IS a Kitchen Sink Pack": "這還真是個大雜燴模組包",
    "All Your Environment Are Belong To Me": "你的環境全都屬於我",
    "Fractioning, I Was Never Good At Math": "分餾，我數學一向不好",
    "Crafting Crafting Seeds to craft Seeds": "用合成種子合成種子",
    "Inferium By Name, Inferium By Reputation": "下級精華，名副其實",
    "The Bauble Breaker": "飾品破壞者",
    "Bauble Breaker": "飾品破壞者",
    "Blame it on the Rain": "都怪這場雨",
    "Starting The Pain Train with Rain": "搭上暴雨痛苦列車",
    "Iron Chef": "鐵人主廚",
    "You Reap What You Sew": "種瓜得瓜，縫啥得啥",
    "Legendary Rune Trade": "傳奇符文交易",
    "Tim The Toolman Taylor": "「工具高手」提姆・泰勒",
    "Nether Gonna Get It": "地獄絕不放過你",
    "Cache Me Outside": "有種到快取外面談",
    "It's Over 9000!": "超過 9000！",
    "Its Greased Lightning": "油光閃電",
    "Shouldn't They Be Called Neckgolds?": "不該叫金項圈嗎？",
    "Dragon Me To Hell": "龍帶我下地獄",
    "WHO'S THE MASTAH!  SHO NUFF!": "誰才是大師？就是我！",
    "O'Dragon Where Art Thou": "龍啊，你在何方",
    "Jetpack to the Future": "噴射背包回到未來",
    "Ender Sharts... er... Shards": "終界碎屎……呃，碎片",
    "Dressed To Compress": "為壓縮盛裝",
    "The Sum Of It All": "總而言之",
    "Infinity Weapon": "無限武器",
    "Flim Flam Flozzel": "花言巧語的騙子",
    "TPS Distress": "TPS 告急",
    "Dongely Doo Neighbor": "轉接器你好啊，鄰居",
    "OreDiction Friction": "礦物辭典摩擦",
    "Barrel O' Laughs": "一桶笑聲",
    "Dragon You With Me": "和我一起龍行嗎？",
}


SOURCE_STARTS_CORRECTIONS = (
    (
        "§6Agricultural Asteroid - §f",
        "§6農業小行星——§f隕石撞上地面後，會顯露出由數十個神秘農業物品方塊構成的本體。其中包含各階級的精華方塊，最高階也包括在內；還有大量生長加速器，可提高農場的整體產量。\n\n啟動墜塔印記儀式時，把§a「神秘肥料」§e§6§f丟到主儀式石上即可召喚這顆隕石。（最好退遠一點。）",
    ),
    (
        "For your bravery and Valor",
        "你的勇氣讓你獲得一枚罕見泰坦符文。可以立刻前往泰坦符文兌換分頁，也可以留待日後使用。  \n\nAsorah 的傳送門鑰匙會指引我們前往下一名泰坦，不過最好先回基地補充物資；這不會是一場輕鬆的戰鬥。",
    ),
)


SOURCE_EXACT_CORRECTIONS = {
    'No Description': '無描述',
    'Your good deeds have netted you Titan Runes!  You can use them in certain crafting recipes, or trade them in for rewards. \n\n§6Tip:  Keep in mind that each Dragon Egg type requires a certain "nest" to incubate in for each variety.  If you simply set it on the ground in a random area, its likely to change to a more common variety of dragon egg.': '你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。 \n\n§6提示：請記住，每種龍蛋都需要在特定的「巢穴」中孵化。如果只是隨意把龍蛋放在地上，它很可能會變成較常見的龍蛋品種。',
    "Your good deeds have netted you Titan Runes!  You can use them in certain crafting recipes, or trade them in for rewards. ": "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。",
    "Difficulty: Hard\nRecommended Magic Level: 70\n\nYou will need to refer to the Arcane Compendium \"Bosses\" Tab for instructions on summoning this Titan.  Also visit am2.wika.com/wiki/Bosses for pictures of the summoning ritual.": "難度：困難\n建議魔法等級：70\n\n請參考奧術大全的「Bosses」分頁，查看召喚這名泰坦的說明。召喚儀式圖片也可造訪 am2.wika.com/wiki/Bosses 。",
    "Difficulty: Hard\n\nRecommended Magic Level: 70\n\nYou will need to refer to the Arcane Compendium \"Bosses\" Tab for instructions on summoning this Titan.  Also visit am2.wika.com/wiki/Bosses for pictures of the summoning ritual.": "難度：困難\n\n建議魔法等級：70\n\n請參考奧術大全的「Bosses」分頁，查看召喚這名泰坦的說明。召喚儀式圖片也可造訪 am2.wika.com/wiki/Bosses 。",
    "Difficulty: Extreme\n\nRecommended Magic Level: 90\n\nYou will need to refer to the Arcane Compendium \"Bosses\" Tab for instructions on summoning this Titan.  Also visit am2.wika.com/wiki/Bosses for pictures of the summoning ritual.": "難度：極限\n\n建議魔法等級：90\n\n請參考奧術大全的「Bosses」分頁，查看召喚這名泰坦的說明。召喚儀式圖片也可造訪 am2.wika.com/wiki/Bosses 。",
    "Fully Charged set of Draconic Weapons": "一套充滿電的龍之武器",
    "To make the more complex tools and weapons from Tinker's Construct you will need a tool forge.": "若要製作匠魂中較複雜的工具與武器，需要先建造工具鍛造台。",
    "To make the more complex tools and weapons from Tinker's Construct you will need a tool forge.\n\n": "若要製作匠魂中較複雜的工具與武器，需要先建造工具鍛造台。\n\n",
    "Each Collosal Chest must have one \"Core\".  This is placed in the middle of one of the outside walls, and §6dictates the direction the chest will be facing.": "每座巨型儲物箱都必須有一個核心，放在其中一面外牆中央；§6核心會決定儲物箱的朝向。",
    "Your good deeds have netted you Titan Runes!  You can use them in certain crafting recipes, or trade them in for rewards. \n\n": "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。\n\n",
    "Your good deeds have netted you Titan Runes!  You can use them in certain crafting recipes, or trade them in for rewards. \n\n§6": "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。\n\n§6",
    "Although some tools you may find in the overworld seem better, there are materials in the Abyssal Dimensions that only respond to the compounds found in Abyssal Tools.  Its wise to always keep a high tier Abyssal Pickaxe on you.\n": "在主世界找到的某些工具看似更強，但深淵維度的部分材料只會對深淵工具所含的特殊成分產生反應。因此最好隨身攜帶一把高階深淵鎬。\n",
    "Your good deeds have netted you Titan Runes!  You can use them in certain crafting recipes, or trade them in for rewards. \n\n§": "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。\n\n§",
    "There are three important goals for your first few days/nights.  Coke Oven, Blast Fuirnace, and Base Defense.": "最初幾天有三個重要目標：焦煤爐、高爐與基地防禦。",
    "There are bigger and more efficient forms of energy to come as you progress through the pack.  For now though, you will need to make some basic generators in order to create materials and start your processing.\n": "隨著模組包進度推進，將會出現規模更大、效率更高的能源。目前仍需先製作一些基礎發電機，才能生產材料並開始加工。\n",
}


SOURCE_CONTAINS_CORRECTIONS = (
    (
        "Use 2 Black Quartz Blocks to make Chiseled Quartz",
        "先用 2 個黑石英方塊合成雕紋石英，再將它們放入原子重構機處理，製成裝飾用石英方塊。",
    ),
    (
        "Love your Angel Ring, but wish you flew faster",
        "喜歡天使指環，卻希望飛得更快？離不開噴射背包，卻嫌它太慢？這件工具能把飛行速度從正常一路調到光速。剛開始很可能一不小心就衝進深淵；反覆按 Shift＋右鍵，速度循環一輪後就會回到正常。",
    ),
    (
        "Providing your base camp with a steady flow of lava",
        "穩定向基地供應熔岩有許多用途。使用遠端幫浦模組，可以把幫浦架在地獄的熔岩湖上，將熔岩抽入終界儲槽，再連接到基地的儲槽。",
    ),
    (
        "Your Airship does NOT have a lot of health",
        "飛空艇的生命值並不高。請記住，一支精準的箭或放錯位置的火焰衝擊，都可能轉眼間把你擊落。",
    ),
    (
        "While low level Armor Plus armor and weapons can be crafted",
        "低階 ArmorPlus 護甲與武器可以在低階工作台製作；更高階的護甲則需要功能更完整的工作台。",
    ),
    (
        "Zombie Flesh, Lapis Dust, and Coal",
        "Tinkers I/O 燃料輸入口使用固體燃料，為冶煉爐提供熔岩的高速替代方案。它把腐肉、青金石粉與煤炭按比例混合成高熱固體，熱值是一塊煤炭的 10 倍。",
    ),
    (
        "This furnace requires no fuel to operate",
        "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。 \n\n§6提示：這座熔爐不需要燃料，每 2 秒就能熔煉 1 個物品，已經比普通熔爐快得多。在側面放置熔岩還能大幅加速，而且仍然不消耗燃料。",
    ),
    (
        "There are three important goals for your first few days/nights",
        "最初幾天有三個重要目標：焦煤爐、高爐與基地防禦。危險很快就會接踵而來，請立刻加固基地，抵禦爆炸、火焰與惱人的掠奪者。  \n\n§6這些階級 1 砲塔基座能協助你開始保衛基地；再完成幾項任務，還會得到額外支援。",
    ),
    (
        "Absorbtion shields are the top tier of absolute damage mitigation",
        "吸收護盾是完全減免傷害的最高階手段。吸收附魔有兩種類型，其中一種附在裝備上，最高可達吸收 V，提供 10 顆心的吸收量。  \n\n另一種來自本頁另一項任務介紹的《吸收之書》，最多可疊加 20 顆心的吸收量。同時使用裝備附魔與書本提供的永久附魔後，總計可取得額外 30 顆心的吸收量，也就是 15 顆心的額外防護！",
    ),
    (
        "Msytical Fertilizer",
        "在 Craft of the Titans 中，你能召喚巨大的隕石從天而降、撞擊地面。煙霧散去後，隕石會依照啟動儀式時使用的「試劑」顯露出礦石或補給品。血魔法的§d墜塔印記儀式加入了三種自訂隕石。§f其中有些物品只能由這些隕石取得，因此價值極高，千萬別忽略這些儀式。\n\n§6農業小行星——隕石撞上地面後，會顯露出由數十個神秘農業物品方塊構成的本體。其中包含各階級的精華方塊，最高階也包括在內；還有大量生長加速器，可提高農場的整體產量。\n\n啟動墜塔印記儀式時，把§a「神秘肥料」§e§6丟到主儀式石上即可召喚這顆隕石。（最好退遠一點。）",
    ),
    (
        "§5§5§f§d Mark Of The Fallen Tower",
        "在 Craft of the Titans 中，你能召喚巨大的隕石從天而降、撞擊地面。煙霧散去後，隕石會依照啟動儀式時使用的「試劑」顯露出礦石或補給品。血魔法的§5§5§f§d墜塔印記儀式加入了三種自訂隕石。§f其中有些物品只能由這些隕石取得，因此價值極高，千萬別忽略這些儀式。\n \n§6儲存之星——隕石撞上地面後，會顯露出完全由精緻儲存元件構成的本體，從儲存磁碟、控制器到合成機器一應俱全。 \n\n§a啟動墜塔印記儀式時，把一枚「石英強化鐵錠」丟到主儀式石上即可召喚這顆隕石。（最好退遠一點。）",
    ),
    (
        "Tier 4 and 5 Turrets, Electric Fences",
        "在 Craft of the Titans 中，你能召喚巨大的隕石從天而降、撞擊地面。煙霧散去後，隕石會依照啟動儀式時使用的「試劑」顯露出礦石或補給品。血魔法的§d墜塔印記儀式加入了三種自訂隕石。§f其中有些物品只能由這些隕石取得，因此價值極高，千萬別忽略這些儀式。\n\n§6軍事隕石——這顆隕石裝滿軍規基地防禦設備，包括無法透過其他途徑取得的階級 4、5 砲塔、電力柵欄、彈藥與升級。召喚過它之後，血月就只會像個笑話。\n\n§l§b§l§l§r§b啟動墜塔印記儀式時，把§b§a「1 階感應器」§b丟到主儀式石上即可召喚這顆隕石。（最好退遠一點。）",
    ),
    (
        "Mekfarm is a compact mod thats based solely around farm automation",
        "MekFarm 是專為農場自動化打造的小型模組。它使用 Tesla 能源；遊戲前期尚無法取得這種能源，必須先讓 MekFarm 運作一段時間，並向§6動物健身房§f供應動物。你也可以繼續推進，利用高等發電機或極限反應爐模組產生 Tesla 能源。 \n§a不過目前先假設你想儘早建好 MekFarm，因此會提供一些已打包的動物協助起步。請記住，如果在設置§6動物健身房§f之前就用完這些動物包裹，之後必須推進到較後期的 Tesla 發電方式，MekFarm 才能繼續運作。",
    ),
    (
        "Natural Absorbtion is a mod the gives you a permanent shield",
        "Craft of the Titans 提供多種方法對付沿途生物。只要用盡所有可用資源，任何戰鬥都不該造成太大問題。如果一直死亡，請按照以下選項逐項檢查，打造更完善的防禦：\n\n§6自然傷害吸收——§f自然傷害吸收模組會提供永久護盾，以一般生命條上方的黃色心顯示。製作接下來幾項任務介紹的自然傷害吸收書，可以增加護盾心數。與施加在護甲上的吸收附魔不同，自然傷害吸收書會永久提高護盾，因此製作與使用書籍都需要昂貴材料及大量 XP。\n§6副手武器——§f本模組包允許雙持。戰鬥平衡是以玩家能同時持有兩把武器，或一把武器搭配盾牌為基礎。別忽略盾牌；任務中能取得某些特殊盾牌，具有荊棘 XXX 或擊退 XX 等特性。\n§e§e§6飾品與附魔——",
    ),
    (
        "§fYou will need to strengthen your resolve and your physical stature",
        "§f若要應付前方的可怕怪物，必須強化自己的意志與體魄。你偶爾能從戰利品袋獎勵或生物掉落物取得心之水晶與心之罐。§6將 9 個心之水晶合成 1 個罐；使用後會永久提高生命值上限。§f最多能把目前生命值加倍，達到完整 30 顆心。再配合遊戲後期提供的自然吸收護盾，或許真的有一戰之力。",
    ),
    (
        "§f§f§6With your new§d Baconator§6",
        "§f§f§6手持新的§d培根供應器§6時按住 Shift，就會把物品欄中適用的食物裝入儲存槽。按住§aShift＋右鍵可啟用自動進食模式。§k§f在此模式下，只要內部還有食物，培根供應器就會持續補充飢餓值。它對食物有些挑剔，但大多數豐收工藝與原版餐點都能使用。若裝入大型餐點，它只會在你非常飢餓時進食，以充分利用食物；若想更頻繁補滿飢餓值，請放入飽食度較低的食物。",
    ),
    (
        "Offer in return, a symbol of the humble beginnings",
        "征服 Ars Magicka 的泰坦絕非易事。為表揚你面對危險時的英勇，請收下這份小小謝禮；作為交換，獻上一件象徵旅程樸素起點的物品——一塊簡單的魔力蛋糕就夠了。",
    ),
    (
        "Thermal Expansion offers a wide variety of",
        "§6§f熱力膨脹提供各式各樣的§a發電機。§f岩漿發電機是非常實用的前期選擇，能把高溫流體轉換成能源；除了熔岩，也能使用 Pyrotheum 等其他高溫流體。",
    ),
    (
        "§6Defeat Asorah and retrieve the Dark Titan Relic",
        "§6擊敗 Asorah，取得她掉落的黑暗泰坦遺物。\n\n§f你的勇氣讓你獲得一枚罕見泰坦符文。可以立刻前往泰坦符文兌換分頁，也可以留待日後使用。  \n\nAsorah 的傳送門鑰匙會指引我們前往下一名泰坦，不過最好先回基地補充物資；這不會是一場輕鬆的戰鬥。",
    ),
    (
        "Assuming you will want to breed Pigs, Cows, Chickens",
        "假設要繁殖豬、牛、雞與羊，就需要共 8 個圍欄，兩兩背靠背排列，從上方看起來像用柵欄圍成的「8」。配置如下：\n\n＋＝柵欄\nB＝繁殖機\nC＝年齡分類機\nD＝研磨機\n\n++++++++++++\n+       +       +\n+       §aC       G\n§f+       +       +\n+++§aB§f++++++++",
    ),
    (
        "Manyullan armor set also comes with",
        "接下來務必把裝備附魔調整到最佳配置。瑪玉靈護甲不只護甲值極高，還提供§c抗性提升 II§f，讓你幾乎堅不可摧。",
    ),
    (
        "The Earth Guardian will do some destrutive damage",
        "大地守護者試圖困住你時，會對方塊造成嚴重破壞。務必遠離基地再與他交戰。",
    ),
    (
        "Be careful exploring underground.  Mobs get tougher",
        "探索地底時務必小心；所在深度越深，生物就越強。",
    ),
    (
        "Higher Level Armors will require more intricate crafting mechanism",
        "高階護甲需要更精密的合成機制。  ",
    ),
    (
        "You will want to get used to having a good amount of treated wood",
        "最好養成隨時備有大量浸漬木板的習慣；許多配方都會用到它。",
    ),
    (
        "The Tinker's Construct Smeltery returns 3 ingots per ore",
        "匠魂冶煉爐每熔煉一份礦石可產出 3 個錠。它或許不是最快的方法，卻能讓採礦收穫發揮最高效率。",
    ),
    (
        "You have been given dual hotbars in this pack for a reason",
        "本模組包提供雙快捷列自有其用意。請利用額外欄位準備緊急用品；隨身帶著降落傘，以防意外發生。",
    ),
    (
        "There are bigger and more efficient forms of energy to come",
        "隨著模組包進度推進，將會出現規模更大、效率更高的能源。目前仍需先製作一些基礎發電機，才能生產材料並開始加工。",
    ),
    (
        "Bows are strong in this pack.  Not only can they apply",
        "本模組包中的弓十分強大。它們不僅能施加各種負面狀態，也能讓你遠離危險。最強的箭是終界龍之箭，會對目標施加§6凋零 IV§f；通常一箭就夠了。熟悉它的配方吧，你可能會經常使用。",
    ),
    (
        "This Boss rarely drops an item called the Arcane Spellbook",
        "難度：困難\n\n建議魔法等級：45\n\n請參考奧術大全的「Bosses」分頁，查看召喚這名泰坦的說明。召喚儀式圖片也可造訪 am2.wika.com/wiki/Bosses 。\n\n§6這名 Boss 有極低機率掉落奧術法術書；它會對後續推進 Ars Magicka 非常有幫助。",
    ),
    (
        "Be careful not to get caught out in the middle of nowhere",
        "太陽開始下山時，千萬別讓自己困在荒郊野外。本模組包中的生物會對聲音、光線與血腥味產生反應，還能挖掘、搭建並炸穿方塊。因此天色漸暗時有兩個選擇：使用方便的新床寵物入睡；或搭一座臨時前哨站，在牆上留幾個能揮劍攻擊的洞口——今晚會很漫長。",
    ),
    (
        "The humid climate and rigorous activity is sure to take its toll",
        "潮濕氣候與劇烈活動肯定會消耗你的體力。§a這個世界中的飢餓值下降得更快。§f善用畫面左下角的§6快速食用食物與藥水列§f，能讓適應過程輕鬆許多。把食物放入其中，需要補充營養時就會自動進食。無論去哪裡都別陷入沒有食物的窘境，否則只會迎來緩慢而痛苦的死亡。請到選項選單查看對應按鍵，再用 Shift 點擊把食物放入快速食用欄位。",
    ),
    (
        "Your journey through this new land has pushed the boundaries",
        "你在新大陸的旅程，將故鄉邊界推向全新的疆域。每片邊疆都需要執法者；而法律的「長臂」若無法伸張正義，又有何用？容我們介紹§6「正義」§f：一把專為你這種久經沙場的士兵所設計的左輪手槍。它懲治敵人的能力，只能由§f§f§f§f持用者§ 的決心與之匹敵。\n\n§6小提示：和本模組包中的多數物品一樣，這把左輪手槍已重新平衡，可作為終局武器使用——別低估它。",
    ),
    (
        "This ring is similar to the Extra Utility Angel ring",
        "征服 Ars Magicka 的泰坦絕非易事。為表揚你面對危險時的英勇，請收下這份小小謝禮。\n\n\n§6小提示§6：這枚指環與更多實用設備的天使指環相似，但能調整飛行速度，而且不需要任何能源。",
    ),
    (
        "The Animal farm is a multi-functional machine",
        "動物農場是一臺多功能機器。  \n－放入剪刀，就會替羊剪毛\n－放入動物包裹，就會把動物打包運送\n－放入桶子，就會替乳牛擠奶\n－放入碗，就會向哞菇取得蘑菇湯\n－放入小麥、種子或胡蘿蔔，就會嘗試餵食動物\n§6它也接受多種過濾器：\n§f同時使用幼體過濾器與動物包裹時，只會打包幼體\n同時使用成體過濾器與動物包裹時，只會打包成體",
    ),
    (
        "There are multiple tiers of furnaces that will speed up",
        "熔爐分成多個階級，可加快基本加工工作。只要用鐵錠包圍普通熔爐，就能把它升級成速度更快、功能更強的版本。\n\n儲物箱也採用相似的階級系統；用對應金屬錠包圍儲物箱，即可提高容量。",
    ),
    (
        "Laser Drills operate by draining ore fragments from the Void",
        "雷射鑽機會從虛空抽取礦石碎片。為此，它與基岩之間必須保持筆直且無遮擋；此外，鑽頭放置的 Y 軸高度越高，效率就越好。也強烈建議使用雷射鑽機預充能器（本獎勵不包含），為鑽頭持續供應 RF 並加快流程。\n\n§6提示：鑽頭通常會撈出各式各樣的礦石，但可使用雷射聚焦器，讓它偏重特定顏色的礦石。",
    ),
    (
        "These Laser Drill Prechargers are used to greatly increase",
        "雷射鑽機預充能器會持續向雷射鑽機供應紅石通量，大幅提高鑽掘速度。",
    ),
    (
        "Reinforced stone is Blast Resistant",
        "只要 1 個石頭和 1 個填縫泥，就能製作堅固的防爆石材，規劃基地時請記住這點。\n\n§a強化石具有防爆能力，能防止惱人的苦力怕與拿炸藥的敵人造成太大破壞，也會阻擋大部分生物破牆進入基地。§9§b然而，仍有少數生物連最堅固的強化石都能打穿。最好建立多層次的防禦系統來保護基地。",
    ),
    (
        "lit glass roof on it",
        "天境的動物習慣在雲端自由飛行，因此飼養時必須做些調整。或許可以建一座帶照明玻璃屋頂的圍欄？",
    ),
    (
        "more powerful armor",
        "粉碎機和 Ender IO 的 SAG 研磨機類似，會把礦石研磨成細粉。這個流程能讓礦物產量加倍，並有機會產生第二種礦物副產品，協助你製作更強的護甲。",
    ),
    (
        "This creative walk speed adjuster does just what it says",
        "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。\n\n§6提示：創造模式步行速度調整器顧名思義能調整步行速度。按住 Shift 點擊即可逐步加速；若超過想要的速度，繼續操作直到循環回正常速度。",
    ),
    (
        "The Decrafting Table may be able to turn them into ingots",
        "在主世界找到的某些工具看似更強，但深淵維度的部分材料只會對深淵工具所含的特殊成分產生反應。因此最好隨身攜帶一把高階深淵鎬。\n\n小提示：從戰利品袋取得了用不到的 Abyssalnite 護甲？拆解台也許能把它還原成金屬錠，再拿來製作工具。",
    ),
    (
        "2 pen setup as follows",
        "若要有條理地大量生產牲畜掉落物，可以採用以下的雙圍欄配置：\n§6繁殖圍欄：§f放入 10～15 對混合牲畜，並設置 2 臺裝有幼體過濾器的動物農場機器。它們會繁殖牲畜，再把幼體打包送往成長圍欄。\n§6成長圍欄：§f這裡只負責容納尚未長成、等待成年後屠宰的幼體。裝有成體過濾器的電動屠宰機會確保牠們長大前不受傷害。可用真空漏斗或儲物箱收集掉落物並送去處理。",
    ),
    (
        "The §aMark Of The Falling Tower§f ritual",
        "第 4 階以上的血魔法血之祭壇能讓你進行儀式。§a墜塔印記§f儀式會召喚隕石從天而降、撞擊地面；煙霧散去後，隕石會依照完成儀式時使用的試劑，化為各種實用補給。除了普通的礦石隕石，還有三種值得召喚的自訂隕石。\n\n§6－精緻儲存隕石裝滿建造大型完整儲存系統所需的一切。  \n－防禦隕石帶有足夠的最高階基地防禦砲塔與補給，連強化得最誇張的煉獄生物也能擊退。  \n－神秘農業隕石堆滿神秘農業種子、精華、生長加速器等物品。 ",
    ),
    (
        "If you fight her out in the open, expect to be fending off",
        "開始看見深淵磚牆時，就表示找到了要塞。請事先規劃與泰坦交戰的位置。如果在戶外開戰，戰鬥期間就得不停抵禦生物與幽靈龍的攻勢。  \n\n§a另一種做法是向下挖到接近基岩層，在石頭中清出一間 20×20、高約 10 格的大房間。在此進行儀式，應能把龍泰坦召喚到受限空間內，讓你不受干擾地戰鬥。你必須按照深淵荒原版本死靈之書的說明設置召喚儀式，把 9 塊深淵鵝卵石排成如下的「時鐘」形狀：\n\n§9 §6§d       O\n    O      O\n   \n  O    O    O \n\n    O      O\n        O \n\n§f（如果這張圖實在太難看懂，請查閱死靈之書的儀式章節。）\n按住 Shift 點擊中央的深淵鵝卵石，使其形成祭壇。柱子出現後：\n\n§6－在 12、3、6、9 點鐘方向各放一個金錠。 \n－在 2 點鐘方向放一顆轉化寶石。  \n－在 4 點鐘方向放一桶液態珊瑚。\n－在 7 點鐘方向放一張附魔台。  \n\n§f所有物品就位後，巡查附近是否有生物或幽靈龍，並先消滅牠們，否則牠們會在戰鬥中治療龍。最後再手持深淵荒原死靈之書，按住 Shift 對祭壇中央柱子點擊右鍵，召喚泰坦。視需要使用藥水、增益蘋果與食物。",
    ),
    (
        "Maybe some lava to fend off pesky critters",
        "遊戲開始時只有一小段時間能讓基地變得安全。之後，危險生物的 AI 會增強，能拆毀牆壁，還會成群結隊不斷伏擊你的位置。處理方式有兩種：盡力加固基地，或在遠離基地的地方建一座小型戰鬥塔，於艱難夜晚和血月期間躲進去。可以用強化石蓋一間 4×4×4 小房間，每面牆留出能揮劍攻擊的縫隙，或許再放些熔岩阻擋惱人的生物。\n\n§6小提示：如果不另外建造血月地堡，就用這些材料鞏固基地。若選擇建造碉堡，請離基地夠遠，確保血月期間基地所在區塊不會保持載入，如此能進一步避免財產損失。",
    ),
    (
        "Instruction Manual titled \"Book Of Absorbtion\"",
        "為了對抗前方無數敵人，故鄉的科學家研發出一種能取得能量護盾、吸收所受傷害的方法。你必須運用每本《吸收之書》說明手冊中的知識，才能施加護盾。奇怪的是，這些書居然能自己合成……因為邏輯就是這樣。\n\n§6提示：合成書籍所需的普通泰坦符文，可在世界各處的地牢儲物箱找到。也可以使用 IndustrialCraft 2 的分子轉換器，把銅方塊轉換成符文。",
    ),
    (
        "place an Entity Detector in the floor of the Growth Pen",
        "自動繁殖牲畜有一個小問題：幼體長大所需的時間，遠比成年動物再次繁殖更久。這表示生長圍欄裡等待成長的幼體會逐漸增加，數量最後可能高得驚人，造成延遲與 TPS 問題。  \n§6為避免這種情況，在生長圍欄地板設置實體偵測器，將偵測範圍調整成恰好覆蓋成長圍欄，再設定成範圍內動物超過 20 隻（或任何你認為安全的數量）時送出紅石訊號。把訊號接到負責餵食繁殖圍欄動物的動物農場機器。簡單來說，只要等待長大的動物超過 20 隻，動物農場就會停止繁殖。",
    ),
    (
        "Chest Interface  or Drawer Controller",
        "EnderIO 物品欄面板以營養蒸餾液為代價，提供大型儲存系統面板的大部分便利功能，而且能與巨型儲物箱、儲存抽屜搭配。只要在儲物箱介面或抽屜控制器上裝一條物品欄導管，放入遠端感知升級，再把 EnderIO 物品欄面板放在另一端——完成！現在可以直接從面板取出、放入，甚至合成物品。\n\n§6提示：可以把營養蒸餾液泵入面板背面，也可以拆下面板，放到 EnderIO 儲槽上補充。小心別把營養蒸餾液用光，否則重新補滿前，只能手動打開儲物箱。",
    ),
    (
        "According to the Compendium, the Arcane Guardian",
        "根據奧術大全，召喚奧術守護者需要名為§6知識神殿§f的結構。先立起兩根高 3 格、相隔 1 格的書櫃柱，再在中間放置裝有奧術大全的講台。 \n\n接著在正前方鋪一圈鐵質鑲嵌，丟入奧術精華，戰鬥便會開始。",
    ),
    (
        "To summon the Winter Guardian, seek out an area",
        "若要召喚寒冬守護者，請尋找一片被寒冬籠罩的區域。在地面鋪設金質鑲嵌圓環，中央用兩個藍色黃玉方塊疊上一個冰，建造寒冬守護者雕像；再於附近製作 3 個雪魔像，為召喚供應能量。",
    ),
    (
        "To summon the Fire Guardian you",
        "召喚火之守護者前必須先進入地獄。建造 3×3 黑曜石框架，頂部放置金質鑲嵌，再於黑曜石圓環中央放一格熔岩源（較新版本則使用煤炭方塊）。最後向熔岩中丟入 2～4 份水之精華（或丟到煤炭方塊上），即可召喚火之守護者。",
    ),
    (
        "Heart Cannisters - §fHeart Crystals increase your base health",
        "Craft of the Titans 提供多種方法對付沿途生物。只要用盡所有可用資源，任何戰鬥都不該造成太大問題。如果一直死亡，請按照以下選項逐項檢查，打造更完善的防禦：\n\n§6心之罐——§f心之水晶能提高基礎生命值，這是增強生存能力最直接的方法。  \n§6副手武器——§f本模組包允許雙持。戰鬥平衡是以玩家能同時持有兩把武器，或一把武器搭配盾牌為基礎。別忽略盾牌；任務中能取得某些特殊盾牌，具有荊棘 XXX 或擊退 XX 等特性。\n§e§e§6飾品與附魔——§f飾品是綁定在飾品上的永久藥水效果，可在物品欄畫面中查看。它們幾乎涵蓋所有防禦與攻擊增益；與物品寵物相似，需要以 BSU 維持運作。  \n§a§e§6魔法——§f魔法不見得適合每個人，但願意嘗試的人能從中獲得極大助益。閃電屏障、火牆、推開敵人的颱風、替你作戰的召喚僕從，應有盡有。鮮為人知的是，本模組包中有些法術只要調整得當，就能一擊殺死遊戲中的任何單一 Boss。你能把魔法調校到足以找到它們嗎？\n§a如果把自己限制在只使用其中一兩種防禦手段，遊玩本模組包的某些部分時勢必會十分吃力。",
    ),
    (
        "§ause this in place of torches as you journey",
        "世界各處生成了閃亮的白藍色液態 Etherium 小池，你在旅途中很可能已經路過。請帶一本書和一個物品展示框前往其中一座池子。抵達後，把展示框放在緊鄰池邊的方塊上，再把書放入展示框。古老符號會開始灌注書本，直到召喚出奧術大全。\n\n§6提示：這項獎勵是你第一次品嚐真正的 Magicka——一支召喚出來、可以投擲的火把。§a旅途中以它取代一般火把，很快就能提升魔法等級。§6把它選到快捷列上，就會看到魔力與耗竭值條出現在畫面中。魔力當然是施放法術所使用的資源；耗盡後，必須等待回復才能再次施法。耗竭值類似「過熱」，短時間內連續施法會提高法術消耗。耗竭值會逐漸冷卻，法術的魔力消耗也會恢復正常。",
    ),
    (
        "Minefactory allows you to automate process of all sorts",
        "MineFactory 能自動化各式各樣的流程，農耕、繁殖、生物農場，甚至大量附魔都只是其中幾個例子。若要及時把補給包送回故鄉，這會是關鍵技術。\n\n塑膠用於各種 MineFactory 配方；最好取得一些橡膠樹苗，確保塑膠原料始終供應充足。",
    ),
    (
        "chemically balanced mixture Turds and Coal Coke",
        "Tinkers I/O 燃料輸入口會把固體燃料快速送入冶煉爐，作為熔岩的高速替代品。它把糞便與焦煤按比例混合成高熱固體，熱值是一塊煤炭的 10 倍。\n\n§6小提示——糞便最常由狗掉落，每隻死亡時掉 2 個；老鼠則掉 1 個。",
    ),
    (
        "§b Place the blocks in the crafting table, or use JEI to view them",
        " \n§6儲存之星——隕石撞上地面後，會顯露出完全由精緻儲存元件構成的本體，從儲存磁碟、控制器到合成機器一應俱全。為避免運送過程中損壞，許多元件都封裝在石頭方塊中。§b把方塊放進合成台，或用 JEI 查看內容；其中的彈性配方方塊可以合成多種元件，用來補齊缺少的設備。\n \n§a啟動墜塔印記儀式時，把一枚「石英強化鐵錠」丟到主儀式石上即可召喚這顆隕石。（最好退遠一點。）",
    ),
    (
        "Blood Moons are but a joke. §f In order to reduce broken package deliveries",
        "\n§6軍事隕石——這顆隕石裝滿軍規基地防禦設備，包括無法透過其他途徑取得的第 4、5 階砲塔、基座、彈藥與升級。召喚過它之後，血月就只會像個笑話。§f為避免運送過程中損壞，許多元件都封裝在石頭方塊中；把方塊放進合成台，或用 JEI 查看內容。\n\n§l§b§l§l§r§b啟動墜塔印記儀式時，把§b§a「1 階感應器」§b丟到主儀式石上即可召喚這顆隕石。（最好退遠一點。）",
    ),
    (
        "This Market block will allow you to trade emeralds",
        "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。\n\n§6提示：市場方塊可以用綠寶石交換世界中的任何種子或樹苗，方便補齊農場仍缺少的稀有品種。",
    ),
    (
        "Some are specifically for transportation (Dragon Mounts Mod)",
        "有些人偏愛飛空艇的可靠性，但情勢艱難時，胯下有強大「火力」再好不過。主世界各地發現了稀有龍；若能把牠們的力量收為己用，誰知道能製造多大的混亂。到平原／沙漠尋找火龍，到最寒冷的生態域尋找冰龍。§3§a尋找牠們的巢穴：焦黑或凍結的凌亂坑地，周圍散落金與銀寶藏。帶一些巢穴材料回來。\n\n§6提示：本模組包並非所有龍都能戰鬥。有些出自《騎乘龍》，專門用於運輸；另一些出自《冰與火》，會噴吐魔法吐息。",
    ),
    (
        "The Phytogenic Insolator Growth Chamber",
        "植物培育機的生長室不必翻耕任何土壤，就能自動種植作物。它使用先進肥料與 RF，複製並培育種子、樹苗及其產物。",
    ),
    (
        "Iron Golems are great at protecting your base",
        "鐵魔像非常適合保護基地：生命值高，攻擊力也十分驚人。到了模組包後期，還能在稀有泰坦符文兌換區換取更多鐵魔像。",
    ),
    (
        "Setting up a Wither Boss Farm",
        "建造凋零怪 Boss 農場，是多數模組包後期的榮譽勳章。你必須把它推進到完全自動化，才能累積足夠的地獄之星，完成這份補給包。",
    ),
    (
        "You will have the ability to place blocks, fire your weapons",
        "駕駛飛空艇時仍可放置方塊、使用武器及投擲手榴彈。正義從天而降！",
    ),
    (
        "run on an energy called BSU",
        "飾品只要裝備著，就會持續提供藥水效果。它們裝在物品欄畫面的專用欄位，並使用名為 BSU 的能量。BSU 由經驗值發電機產生；顧名思義，這臺機器會把玩家經驗值轉換成 BSU。",
    ),
    (
        "The ultimate flying apparatus... the Angel Ring",
        "終極飛行裝備——天使指環。不需要燃料，也不必充電；只要在更多實用設備的電網中保有足夠的可用 GP 即可。當然，你也可以繼續駕駛那艘出色的飛空艇。",
    ),
    (
        "it will cost Experience levels to apply it,  and Lapis Lazuli",
        "吸收來襲傷害是一項極強的能力，不能隨意授予。為了確認你足以承擔這份力量，每次套用書本都會消耗經驗等級，製作書本也需要青金石。對你這樣的英雄而言應該不成問題；生物農場或神秘農業作物都能提供大量 XP。",
    ),
    (
        "The Environmental Controller GUI has the option",
        "環境控制器的 GUI 可以指定已安裝增益要覆蓋的座標範圍。例如，若想在與終界龍戰鬥時讓飛行效果覆蓋整座終界島，就要把控制器放在島嶼中央，再設定覆蓋 Y60（島嶼高度）與 X75（控制器周圍半徑 75 格）。這只是範例，仍需自行測試，確認範圍是否完整覆蓋。受到控制器保護時，周圍會出現增益粒子。",
    ),
    (
        "Do not underestimate the power of a well time potion",
        "你會帶著火把、工具、武器、寵物等各種物品進入戰鬥。別低估適時使用藥水的力量；一瓶用得恰到好處的藥水，足以替你扭轉戰局。",
    ),
    (
        "This aint your grandfather's revolver",
        "你的善行為你贏得了泰坦符文！可以用於特定合成配方，也能拿來兌換獎勵。\n\n§3小提示：這可不是你祖父的左輪手槍，而是§4重新平衡、威力驚人的§3§4沉浸工程左輪手槍§3，還配有穿甲彈。若要安裝升級，必須使用工程師工作台。\n\n對了，這些西部風格的左輪手槍還能雙持！",
    ),
    (
        "The Recycler is a machine that accepts common items",
        "回收機會接收普通物品加以回收，並有機率產生廢料。9 個廢料可以合成一個廢料盒，打開後會得到一件蠢得毫無用處的物品。也可以把廢料或廢料盒放進物質製造機。這非常重要；等你製作物質製造機時，會再詳細說明原因。目前只要知道，處理廢料是提升後期效率的重要環節。\n\n§6提示：有一個好消息和一個壞消息。壞消息是，不能再像以前的模組包一樣直接把鵝卵石丟進回收機，回收工廠已將它列入黑名單。好消息是，回收機幾乎仍接受其他所有材料，而且已開發出製造廢料的新方法，因此產量應不會改變。詳情請查看《泰坦之戰》提示指南。  ",
    ),
    (
        "For the purpose of these quests we will assume you are going with an all around, efficient 7x7x5 Reactor",
        "網路上有許多資料可供研究，幫助你找出最適合自己的配置。為了進行這些任務，我們假設你會採用兼顧各方面效率的 7×7×5 反應爐，並在中央把 5 根燃料棒排成「X」形。\n\n§3小提示：每座反應爐都必須在外殼內、燃料棒周圍放置固體或液體冷卻劑。這能大幅降低熱量並提升燃料效率。目前最經濟的選擇很可能是石墨，但效果最好的冷卻劑是§6輕盈蒸氣§b§3；升級成蒸汽渦輪機時，我們就會改用它。",
    ),
    (
        "You will receive a 3 day buffer of peace",
        "你會獲得三天的和平緩衝期；這段時間內，任何生物都無法進入放置生物阻擋器的區塊。希望你把它放在基地周圍，因為生物具有一些破壞能力。效果結束後，真正的地獄就會降臨。生物會想盡辦法接近你，無處可以躲藏。鑽入地下只會讓深處的生物追獵；牠們已獲得合適工具，確保地下基地同樣充滿挑戰。  \n\n§6簡而言之：利用最初三天，採用任何找得到的便宜方法鞏固基地。有些任務甚至會提供地面尖刺、砲塔或柵欄，幫助你做好防禦。\n\n提示：生物會受活塞或礦石研磨機等聲音吸引，也會被室外火把等光源吸引。因此請明智規劃基地，才能擊退生物……或從一開始就別把牠們引來。",
    ),
    (
        "At some point towards the start of your 2nd week",
        "第二週剛開始不久，就該考慮利用飛空艇提升探索能力。它們就像你的私人噴射機，能載你前往世界各地。飛空艇共有 4 個階級，每升一階速度都會提高。\n\n為了跟上新科技的需求，請確認自己已開始自動化礦石處理。匠魂冶煉爐每份礦石能產出 3 個錠，但需要更多空間與巧思；你也可以選擇機器式礦石處理，不過代價是消耗 RF，而且會少拿那額外的一個錠。\n\n§6你也應該開始推進 AbyssalCraft。部分後期泰坦懸賞會把你帶回 AbyssalCraft 深處，以取得強大的泰坦符文。",
    ),
    (
        "Every spell is created from a combination of 3 traits",
        "每個法術都由三種特性組合而成。  \n\n§6「形態」特性§b§6§b決定法術如何行動或移動，每個法術都必須具備一種形態：它是向前射出的投射物？停在原地漂浮的法球？施加在自己身上的靈氣？還是涵蓋廣大區域的範圍效果？\n\n§6「構件」特性§b決定法術由什麼構成，每個法術都必須具備一種構件：它以火焰為基礎，還是由閃電組成？魔法構件共有五種不同學派，各自具有不同的附帶效果與魔力消耗。\n\n§6「修飾」特性§b是法術的選用附加項目，用來強化法術的某項特性，包括傷害、持續時間、效力、射程、半徑、彈跳、穿透等許多效果。",
    ),
    (
        "To summon the powerful Ender Guardian",
        "若要召喚強大的終界守護者，請前往終界，在 3×3 煤炭方塊方形中央上方建造夜黑之耳，再用金質鑲嵌把它完整包圍。接著用打火石，在四個方向的鑲嵌外側點火。最後獻上一份終界精華與一顆終界之眼，使夜黑之耳失穩。",
    ),
)


# Longer entries are applied first.  This deliberately translates ordinary
# item, block, creature, dimension and mechanic names while retaining only
# brands, abbreviations and coined names whose English form aids recognition.
TERM_REPLACEMENTS = (
    ("Soulium Dagger", "離魂匕首"),
    ("Soulium", "離魂"),
    ("Pool of Etherium", "以太之池"),
    ("Liquid Etherium", "液態以太"),
    ("Etherium", "以太"),
    ("Grimoire of Gaia", "蓋亞魔典"),
    ("Grimoire of Gaie", "蓋亞魔典"),
    ("Tome of Alkahestry", "萬能溶劑之經"),
    ("Vinteum Dust", "溫特姆粉末"),
    ("Vinteum", "溫特姆粉末"),
    ("Aurem", "夜黑之耳"),
    ("Occulus", "全知之眼"),
    ("Aums", "全知草"),
    ("Aum", "全知草"),
    ("Stoneburnt blocks", "燒製石頭方塊"),
    ("Stoneburnt", "燒製石頭"),
    ("Sheepuffs", "雲跳羊"),
    ("Sheepuff", "雲跳羊"),
    ("Black Moa", "黑色恐鳥"),
    ("Moas", "恐鳥"),
    ("Moa", "恐鳥"),
    ("Grue", "格魯"),
    ("Phygs", "飛天豬"),
    ("Phyg", "飛天豬"),
    ("Kappa Pick", "Kappa鎬"),
    ("Pickappa", "Kappa鎬"),
    ("Casull Cartridge", "卡蘇爾彈"),
    ("Casull", "卡蘇爾彈"),
    ("Inferium Essence", "下級精華"),
    ("Inferium Seeds", "下級種子"),
    ("Inferium", "下級"),
    ("Blocks of Ludicrite", "鎦方塊"),
    ("Ludicrite blocks", "鎦方塊"),
    ("Ludicrite Blocks", "鎦方塊"),
    ("Ludicrite", "鎦"),
    ("Cyanite", "藍晶"),
    ("Abyssalnite", "淵素"),
    ("Gelid Cryotheum", "極寒之凜冰"),
    ("Blazing Pyrotheum", "烈焰之熾焱"),
    ("Cryotheum", "凜冰"),
    ("Pyrotheum", "熾焱"),
    ("Ars Magicka Elemental Titans", "Ars Magicka 元素泰坦"),
    ("Slice and Splice", "切片拼接機"),
    ("Slice 'n' Splice", "切片拼接機"),
    ("Vein Miner", "礦脈挖掘"),
    ("VeinMiner", "礦脈挖掘"),
    ("AbyssalCraft Wiki", "AbyssalCraft 維基"),
    ("Wiki", "維基"),
    ("Quartz Enriched Iron Ingot", "石英強化鐵錠"),
    ("Armor Piercing Bullet", "穿甲彈"),
    ("Armor Piercing", "穿甲彈"),
    ("Actively Cooled Reactor", "主動冷卻反應爐"),
    ("Environmental Controller", "環境控制器"),
    ("Molecular Transformer", "分子轉換器"),
    ("Advanced Blast Furnace", "高等高爐"),
    ("Mass Fabricator", "物質製造機"),
    ("Master Ritual Stone", "主儀式石"),
    ("Mark of the Falling Tower", "墜塔印記"),
    ("Mark of the Fallen Tower", "墜塔印記"),
    ("dMark of the Fallen Tower", "墜塔印記"),
    ("Life Essence Network", "生命源質網路"),
    ("Mystical Agriculture Meteor", "神秘農業隕石"),
    ("Refined Storage Meteor", "精緻儲存隕石"),
    ("Military Meteor Reagent", "軍事隕石試劑"),
    ("Military Meteor", "軍事隕石"),
    ("Defense Meteor", "防禦隕石"),
    ("Ore Meteor", "礦石隕石"),
    ("Growth Accelerator", "生長加速器"),
    ("Flexible Recipe Block", "彈性配方方塊"),
    ("Black Quartz Block", "黑石英方塊"),
    ("Blue Topaz Block", "藍色黃玉方塊"),
    ("Reinforced Stone", "強化石"),
    ("Abyssal Cobblestone", "深淵鵝卵石"),
    ("Stone Block", "石頭方塊"),
    ("Coal Block", "煤炭方塊"),
    ("Market Block", "市場方塊"),
    ("Blood Magic Blood Altar Upgrades", "《血魔法血之祭壇升級指南》"),
    ("Blood Magic Blood Altar Guide", "《血魔法血之祭壇指南》"),
    ("Blood Magic Bound Armor", "血魔法束縛護甲"),
    ("Blood Magic", "血魔法"),
    ("Blood Altar", "血之祭壇"),
    ("Blood Arsenal", "血之軍械庫"),
    ("Blood Orb", "血之寶珠"),
    ("Weak Blood Shard", "弱血之碎片"),
    ("Life Essence", "生命源質"),
    ("Demon Will", "惡魔意志"),
    ("Crystallized Will", "結晶意志"),
    ("Sentient Sword", "感知之劍"),
    ("Tartaric Gem", "塔爾塔洛斯寶石"),
    ("Hellfire Forge", "獄火鍛爐"),
    ("Divination Sigil", "占卜印記"),
    ("Alchemy Array", "煉金法陣"),
    ("Crafting Altar", "合成祭壇"),
    ("Arcane Compendium", "奧術大全"),
    ("Arcane Guardian", "奧術守護者"),
    ("Water Guardian", "水之守護者"),
    ("Earth Guardian", "大地守護者"),
    ("Air Guardian", "風之守護者"),
    ("Life Guardian", "生命守護者"),
    ("Nature Guardian", "自然守護者"),
    ("Lightning Guardian", "雷霆守護者"),
    ("Winter Guardian", "寒冬守護者"),
    ("Fire Guardian", "火之守護者"),
    ("Ender Guardian", "終界守護者"),
    ("Guardian Armor", "守護者護甲"),
    ("Chaos Guardian Dragon", "混沌守護龍"),
    ("Valkyrie Queen", "女武神女王"),
    ("Valkyrie Armor", "女武神護甲"),
    ("Dragon's Breath", "龍息彈"),
    ("Spectral Dragon", "幽靈龍"),
    ("Dragon Titan", "龍泰坦"),
    ("Fire Dragon", "火龍"),
    ("Ice Dragon", "冰龍"),
    ("Dragon Egg", "龍蛋"),
    ("Dragon Flight", "龍之飛行"),
    ("Ender Pearl", "終界珍珠"),
    ("Eye of Ender", "終界之眼"),
    ("Ender Shard", "終界碎片"),
    ("Ender Chest", "終界箱"),
    ("Broken Spawner", "損壞的生怪磚"),
    ("Soul Binder", "靈魂綁定機"),
    ("Soul Vial", "靈魂瓶"),
    ("Rotten Flesh", "腐肉"),
    ("Infinity Orb", "無限寶珠"),
    ("Infinity Armor", "無限護甲"),
    ("Obsidian Armor", "黑曜石護甲"),
    ("Leather Armor", "皮革護甲"),
    ("Chest Armor", "胸甲"),
    ("Dark Steel Armor", "暗黑鋼護甲"),
    ("Mage Armor", "法師護甲"),
    ("Manyullyn Armor", "瑪玉靈護甲"),
    ("Ultimate Armor", "終極護甲"),
    ("The Aether", "天境"),
    ("The Beneath", "地底世界"),
    ("The End", "終界"),
    ("Abyssal Wasteland", "深淵荒原"),
    ("Nether", "地獄"),
    ("Old Gods", "舊日諸神"),
    ("Blood Moon", "血月"),
    ("Thermal Expansion", "熱力膨脹"),
    ("Tinkers' Construct", "匠魂"),
    ("Tinkers’ Construct", "匠魂"),
    ("Mystical Agriculture", "神秘農業"),
    ("Refined Storage", "精緻儲存"),
    ("Storage Drawers", "儲存抽屜"),
    ("Cooking for Blockheads", "烹飪傻瓜書"),
    ("Actually Additions", "實用拓展"),
    ("Extra Utilities 2", "更多實用設備 2"),
    ("Extra Utilities", "更多實用設備"),
    ("Immersive Engineering", "沉浸工程"),
    ("Draconic Evolution", "龍之進化"),
    ("Extreme Reactors", "極限反應爐"),
    ("Extreme Reactor", "極限反應爐"),
    ("Advanced Generators", "高等發電機"),
    ("Advanced Generator", "高等發電機"),
    ("Colossal Chest", "巨型儲物箱"),
    ("Cooking Table", "烹飪台"),
    ("Crafting Table", "合成台"),
    ("Enchanting Table", "附魔台"),
    ("Inscription Table", "銘文台"),
    ("Engineer's Workbench", "工程師工作台"),
    ("Engineers Workbench", "工程師工作台"),
    ("Tool Forge", "工具鍛造台"),
    ("Coke Oven", "焦煤爐"),
    ("Blast Furnace", "高爐"),
    ("Redstone Furnace", "紅石熔爐"),
    ("Induction Smelter", "感應冶煉爐"),
    ("Alloy Smelter", "合金冶煉爐"),
    ("Tinkers' Smeltery", "匠魂冶煉爐"),
    ("Tinkers’ Smeltery", "匠魂冶煉爐"),
    ("Sag Mill", "SAG 研磨機"),
    ("Water Mill", "水力磨坊"),
    ("Water Wheel", "水車"),
    ("Windmill", "風車"),
    ("Solar Panel", "太陽能板"),
    ("Quantum Solar Panel", "量子太陽能板"),
    ("Steam Turbine", "蒸汽渦輪機"),
    ("Gas Turbine Controller", "燃氣渦輪控制器"),
    ("Gas Turbine Generator", "燃氣渦輪發電機"),
    ("Gas Turbine", "燃氣渦輪機"),
    ("Nuclear Reactor", "核反應爐"),
    ("Power Cell Card", "能量電池卡"),
    ("Power Cell", "能量電池"),
    ("Energy Emitter", "能量發射器"),
    ("Fluid Intake", "流體輸入口"),
    ("Rocket Fuel", "火箭燃料"),
    ("Nutrient Distillation", "營養蒸餾液"),
    ("Redstone Flux", "紅石通量"),
    ("Grid Power", "電網能量"),
    ("Culinary Generator", "烹飪發電機"),
    ("Environmental Tech", "環境科技"),
    ("Atomic Reconstructor", "原子重構機"),
    ("Macerator", "打粉機"),
    ("Metal Former", "金屬成型機"),
    ("Pulverizer", "粉碎機"),
    ("Crusher", "粉碎機"),
    ("Compactor", "壓縮機"),
    ("Recycler", "回收機"),
    ("Replicator", "複製機"),
    ("Teleporter", "傳送器"),
    ("Refrigerator", "冰箱"),
    ("Vacuum Chest", "真空儲物箱"),
    ("Storage Drawer", "儲存抽屜"),
    ("Chest Interface", "儲物箱介面"),
    ("Pattern Storage", "樣板儲存器"),
    ("Inventory Panel", "物品欄面板"),
    ("Capacitor", "電容器"),
    ("Conduit", "導管"),
    ("Adult Filter", "成體過濾器"),
    ("Speed Upgrade", "速度升級"),
    ("Upgrade", "升級"),
    ("Care Package Daily", "每日補給包"),
    ("Care Package", "補給包"),
    ("Animal Package", "動物補給包"),
    ("Animal Farm", "動物農場"),
    ("Animal Gym", "動物健身房"),
    ("Artifact Bag", "遺物袋"),
    ("Loot Bag", "戰利品袋"),
    ("Scrap Box", "廢料盒"),
    ("Heart Canister", "心之罐"),
    ("Ability Totem", "能力圖騰"),
    ("Angel Ring", "天使指環"),
    ("Angelheart Vial", "天使之心藥瓶"),
    ("Titan Rune Trade In", "泰坦符文兌換"),
    ("Uncommon Titan Rune", "罕見泰坦符文"),
    ("Rare Titan Rune", "稀有泰坦符文"),
    ("Titan Rune", "泰坦符文"),
    ("Ore Dictionary", "礦物辭典"),
    ("Gold Ingot", "金錠"),
    ("Copper Ingot", "銅錠"),
    ("Gold Inlay", "金質鑲嵌"),
    ("Iron Inlay", "鐵質鑲嵌"),
    ("Coralium Ore", "珊瑚礦石"),
    ("Coralium Gem", "珊瑚寶石"),
    ("Transmutation Gem", "轉化寶石"),
    ("Ethetic Quartz Blocks", "裝飾用石英方塊"),
    ("Ethetic Quartz", "裝飾用石英"),
    ("Chiseled Quartz", "雕紋石英"),
    ("Black Quartz", "黑石英"),
    ("Quartz", "石英"),
    ("Treated Wood", "防腐木"),
    ("Cobblestone", "鵝卵石"),
    ("Obsidian", "黑曜石"),
    ("Redstone", "紅石"),
    ("Neutronium", "中子素"),
    ("Iridium", "銥"),
    ("Sunnarium", "陽光化合物"),
    ("Diamond", "鑽石"),
    ("Copper", "銅"),
    ("Steel", "鋼"),
    ("Iron", "鐵"),
    ("Gold", "金"),
    ("Coal", "煤炭"),
    ("Clay", "黏土"),
    ("Dirt", "泥土"),
    ("Plank", "木板"),
    ("Lava Source", "熔岩源"),
    ("Lava", "熔岩"),
    ("Ice", "冰"),
    ("Snowball", "雪球"),
    ("Bucket", "桶"),
    ("Ingot", "錠"),
    ("Plate", "板"),
    ("Casing", "外殼"),
    ("Ore", "礦石"),
    ("Block", "方塊"),
    ("Torch", "火把"),
    ("Hopper", "漏斗"),
    ("Item Frame", "物品展示框"),
    ("Pattern", "樣板"),
    ("Workbench", "工作台"),
    ("Furnace", "熔爐"),
    ("Smeltery", "冶煉爐"),
    ("Generator", "發電機"),
    ("Reactor", "反應爐"),
    ("Turbine", "渦輪機"),
    ("Controller", "控制器"),
    ("Interface", "介面"),
    ("Filter", "過濾器"),
    ("Spawner", "生怪磚"),
    ("Crafter", "合成器"),
    ("Airship", "飛空艇"),
    ("Jetpack", "噴射背包"),
    ("Revolver", "左輪手槍"),
    ("Buckshot Cartridge", "霰彈筒"),
    ("Silver Bullet", "銀彈"),
    ("Ammo", "彈藥"),
    ("Sword", "劍"),
    ("Shield", "盾牌"),
    ("Dagger", "匕首"),
    ("Hammer", "錘"),
    ("Bow", "弓"),
    ("Armor", "護甲"),
    ("Guardian", "守護者"),
    ("Guardians", "守護者"),
    ("Wither", "凋零怪"),
    ("Creeper", "苦力怕"),
    ("Dryad", "樹精"),
    ("Valkyrie", "女武神"),
    ("Dragon", "龍"),
    ("Titan", "泰坦"),
    ("Titans", "泰坦"),
    ("Meteor", "隕石"),
    ("Dungeon", "地牢"),
    ("Mob", "生物"),
    ("Mana Pool", "魔力池"),
    ("Mana", "魔力"),
    ("Burnout", "耗竭值"),
    ("Essence", "精華"),
    ("Reagent", "試劑"),
    ("Ritual", "儀式"),
    ("Altar", "祭壇"),
    ("Bauble", "飾品"),
    ("Charm", "護符"),
    ("Will", "意志"),
    ("Absorption", "吸收"),
    ("Singularity", "奇點"),
    ("Scrap", "廢料"),
    ("Fluid", "流體"),
    ("Energy", "能量"),
    ("Power", "能源"),
    ("Fuel", "燃料"),
    ("Seed", "種子"),
    ("Shape", "形態"),
    ("Component", "構件"),
    ("Tier", "階級"),
    ("Ring", "指環"),
    ("Stone", "石頭"),
    ("Earth", "大地"),
    ("Necronomicon", "死靈之書"),
    ("UU-Matter", "UU 物質"),
    ("Engineer's Hammer", "工程師之錘"),
    ("Engineer's 錘", "工程師之錘"),
    ("Engineer's", "工程師的"),
    ("Engineer", "工程師"),
    ("Liquid Coralium", "液態珊瑚"),
    ("Refined Coralium", "精煉珊瑚"),
    ("Growth Pen", "生長圍欄"),
    ("Extreme Crafting", "終極合成"),
    ("Spot Loader", "定點區塊載入器"),
    ("Rotor Shaft", "轉子軸"),
    ("Induction Coil", "感應線圈"),
    ("RFTools Builder", "RFTools 建築機"),
    ("Witchwood Tree", "巫木樹"),
    ("Gateway Key", "傳送門鑰匙"),
    ("Coffee Maker", "咖啡機"),
    ("Black Aurem", "夜黑之耳"),
    ("Turret Base", "砲塔基座"),
    ("Abyssal Tool", "深淵工具"),
    ("Abyssal Pickaxe", "深淵鎬"),
    ("Fire Water", "火焰水"),
    ("Blank Slate", "空白石板"),
    ("Agricultural Asteroid", "農業小行星"),
    ("Mystical Fertilizer", "神秘肥料"),
    ("Storage Star", "儲存之星"),
    ("Storage Disk", "儲存磁碟"),
    ("Quick Consume", "快速食用"),
    ("Powerstone Tracker", "能量石追蹤器"),
    ("Abyssal Brick", "深淵磚"),
    ("Buff Apple", "增益蘋果"),
    ("Aether Livestock", "天境牲畜"),
    ("Cooking Oil", "食用油"),
    ("Sun Spirit", "太陽精靈"),
    ("CFB Kitchen", "CFB 廚房"),
    ("Storage System", "儲存系統"),
    ("Remote Awareness", "遠端感知"),
    ("Knockback", "擊退"),
    ("Heart Crystal", "心之水晶"),
    ("Laser Drill Precharger", "雷射鑽機預充能器"),
    ("Laser Drill", "雷射鑽機"),
    ("Veterinary Station", "獸醫站"),
    ("Fire Protection", "火焰防護"),
    ("Fire Elemental", "火元素"),
    ("Mage Robe", "法師長袍"),
    ("Leather Camo", "皮革迷彩"),
    ("Solar Powered Turret Defense Gun", "太陽能砲塔防禦槍"),
    ("Yellorite Ingot", "黃鈾錠"),
    ("Yellorite", "黃鈾礦"),
    ("Yellorium", "黃鈾"),
    ("Blutonium", "藍鈽"),
    ("Charging Station", "充電站"),
    ("Victory Medal", "勝利獎章"),
    ("Casting Table", "鑄造台"),
    ("Washing Plant", "洗礦廠"),
    ("Thermal Mediator", "熱力調節器"),
    ("Dark Glass", "暗色玻璃"),
    ("Slime Boots", "史萊姆靴子"),
    ("Feather Falling", "輕盈"),
    ("Ocean Monument", "海底神殿"),
    ("Disenchantment Table", "祛魔台"),
    ("Chunk Loader", "區塊載入器"),
    ("Solid Canning Machine", "固體裝罐機"),
    ("Dismounter Tool", "卸除工具"),
    ("Illuminati Pet", "光明會寵物"),
    ("Infernal Tear", "煉獄之淚"),
    ("Crystal Wrench", "水晶扳手"),
    ("Celestial Prism", "天界稜鏡"),
    ("End Portal", "終界傳送門"),
    ("Fractionating Still", "分餾蒸餾器"),
    ("Phoenix Down", "鳳凰羽"),
    ("Angelic Feather", "天使羽毛"),
    ("Item Repairer", "物品修復機"),
    ("Lapis Dust", "青金石粉"),
    ("Igneous Extruder", "火成岩擠壓機"),
    ("Glacial Precipitator", "冰川沉澱機"),
    ("Aqueous Accumulator", "蓄水器"),
    ("Memory Crystal", "記憶水晶"),
    ("Grinding Ball", "研磨球"),
    ("Oak Wood", "橡木"),
    ("Healing Station", "治療站"),
    ("Arcane Spellbook", "奧術法術書"),
    ("Starter House Kit", "新手小屋套件"),
    ("Disposable Turret", "拋棄式砲塔"),
    ("Sprinkler", "灑水器"),
    ("Decrafting Table", "拆解台"),
    ("Energy Unit", "能量單位"),
    ("Creosote Oil", "雜酚油"),
    ("Fuel Tank", "燃料槽"),
    ("Fluid Input Valve", "流體輸入閥"),
    ("Geothermal Generator", "地熱發電機"),
    ("Wireless Charger", "無線充電器"),
    ("Handheld Filler", "手持填充器"),
    ("Lapis Lamp", "青金石燈"),
    ("Hazmat Suit", "防護衣"),
    ("Arboreal Extractor", "樹液提取器"),
    ("Resin", "樹脂"),
    ("Rosin", "松香"),
    ("Rubber", "橡膠"),
    ("Binder", "黏合劑"),
    ("Cable Insulation", "纜線絕緣層"),
    ("Cable", "纜線"),
    ("Frame", "機架"),
    ("Colorizer", "著色器"),
    ("Array", "陣列"),
    ("Rare", "稀有"),
    ("Legendary", "傳奇"),
    ("Archaic", "遠古"),
    ("Poison", "中毒"),
    ("Weakness", "虛弱"),
    ("Totem", "圖騰"),
    ("Kitchen", "廚房"),
    ("Cabinet", "櫥櫃"),
    ("Sink", "水槽"),
    ("Bunker", "地堡"),
    ("Book", "書"),
    ("Core", "核心"),
    ("Dynamo", "發電機"),
    ("Chunk", "區塊"),
    ("Chest", "儲物箱"),
    ("Input", "輸入口"),
    ("Thorns", "荊棘"),
    ("Enderman", "終界使者"),
    ("Ender", "終界"),
    ("Tank", "儲槽"),
    ("Stirling", "史特林"),
    ("Grinder", "研磨機"),
    ("Baubles", "飾品"),
    ("Snow", "雪"),
    ("Emerald", "綠寶石"),
    ("Sand", "沙"),
    ("Arrow", "箭"),
    ("Dynamite", "炸藥"),
    ("Pellet", "彈丸"),
    ("Pickaxe", "鎬"),
    ("Chaos", "混沌"),
    ("Factory", "工廠"),
    ("Pump", "幫浦"),
    ("Pressure", "壓力"),
    ("Ability", "能力"),
    ("Crude", "粗製"),
    ("Nuclear", "核能"),
    ("Pumpkin Pie", "南瓜派"),
    ("Sacrificial", "犧牲"),
    ("Rune", "符文"),
    ("Crafting", "合成"),
    ("Diviner", "占卜器"),
    ("Sensor", "感應器"),
    ("Projectile", "投射物"),
    ("Infernal", "煉獄"),
    ("Coralium", "珊瑚"),
    ("Stronghold", "要塞"),
    ("Rituals", "儀式"),
    ("Silver", "銀"),
    ("Fisher", "捕魚機"),
    ("Worm", "蠕蟲"),
    ("Toolbelt", "工具腰帶"),
    ("Skeleton", "骷髏"),
    ("Relic", "遺物"),
    ("Chicken", "雞"),
    ("Syringe", "注射器"),
    ("Experience", "經驗值"),
    ("Belt", "腰帶"),
    ("Extractor", "提取器"),
    ("Hunter", "獵人"),
    ("Cave", "洞穴"),
    ("Shard", "碎片"),
    ("Neutron", "中子"),
    ("Collector", "收集器"),
    ("Dummy", "假人"),
    ("Affinity", "親和力"),
    ("Great Old God", "偉大舊日神"),
    ("Old God", "舊日神"),
    ("God", "神"),
    ("Lieutenant", "中尉"),
    ("Sanctum", "聖所"),
    ("Scale", "鱗片"),
    ("Himalayas", "喜馬拉雅山"),
    ("Yeti", "雪怪"),
    ("Gadget", "裝置"),
    ("Cobble", "鵝卵石"),
    ("Dongle", "轉接器"),
    ("Portable", "可攜式"),
    ("Sawmill", "鋸木機"),
    ("Faucet", "澆注口"),
    ("Empowerer", "賦能器"),
    ("Reconstructor", "重構機"),
    ("Scanner", "掃描器"),
    ("Parachute", "降落傘"),
    ("Golem", "魔像"),
    ("Star", "星"),
    ("Zombie", "殭屍"),
    ("Propellant", "推進劑"),
    ("Swab", "棉棒"),
    ("Advanced", "高等"),
    ("Looting", "掠奪"),
    ("Beheading", "斬首"),
    ("Sharpness", "鋒利"),
    ("Banana", "香蕉"),
    ("Angel", "天使"),
    ("Obelisk", "方尖碑"),
    ("Blue", "藍色"),
    ("Green", "綠色"),
    ("Red", "紅色"),
    ("Orb", "寶珠"),
    ("Oven", "烤箱"),
    ("Sapling", "樹苗"),
    ("Flint", "燧石"),
    ("Transposer", "轉移器"),
    ("Nest", "巢穴"),
    ("Dark Diamond", "暗黑鑽石"),
    ("Darkland Mountains", "黑暗之地山脈"),
    ("Darklands Mountain", "黑暗之地山脈"),
    ("Dreadlands Mountain", "恐懼之地山脈"),
    ("Dreadlands Infused Powerstone", "恐懼之地灌注能量石"),
    ("Coralium Infested Swamp", "珊瑚侵染沼澤"),
    ("Abyssal Plague", "深淵瘟疫"),
    ("AbyssalCraft Wiki", "AbyssalCraft Wiki"),
    ("Spawn of Cha'Garoth", "Cha'Garoth 之子"),
    ("Asorah's Gateway Key", "Asorah 的傳送門鑰匙"),
    ("Killer Joe", "殺手喬"),
    ("The Vat", "發酵桶"),
    ("The Ender", "終界採石場"),
    ("Ender Tether", "終界拴繩"),
    ("End Island", "終界島"),
    ("EnderIO Tank", "EnderIO 儲槽"),
    ("EnderIO Smelter", "EnderIO 冶煉爐"),
    ("EnderIO SAG", "EnderIO SAG 研磨機"),
    ("IC2 Canner", "IC2 裝罐機"),
    ("IC2 Coolant", "IC2 冷卻液"),
    ("Tinker's Construct", "匠魂"),
    ("Tinkers I/O Smart Output", "Tinkers I/O 智慧輸出"),
    ("Smart Output", "智慧輸出"),
    ("Tinkers I/O Stirling", "Tinkers I/O 史特林"),
    ("Steve's Carts", "Steve's Carts"),
    ("Applied Energistics", "應用能源"),
    ("Free GP", "免費 GP"),
    ("Industrial Hemp", "工業大麻"),
    ("Tough Fabric", "強韌布料"),
    ("Transfer Pipe", "傳輸管線"),
    ("Vapor of Levity", "輕盈蒸氣"),
    ("Well of Suffering", "苦難之井"),
    ("Open Modular Turrets", "開放式模組化砲塔"),
    ("Infested Biome", "侵染生態域"),
    ("Vies Airships", "Vies 飛空艇"),
    ("Creative Walk Speed Adjuster", "創造模式步行速度調整器"),
    ("Aether Grass", "天境草方塊"),
    ("Aether Berry", "天境莓果"),
    ("Nature Scythe", "自然鐮刀"),
    ("Dark Knight", "暗黑騎士"),
    ("Bed Pet", "床寵物"),
    ("Molten Metal", "熔融金屬"),
    ("MekFarm Electric Butcher", "MekFarm 電動屠宰機"),
    ("RS Network", "RS 網路"),
    ("Overclocker", "超頻升級"),
    ("Control Rod", "控制棒"),
    ("Coolant Port", "冷卻液連接埠"),
    ("Turret Cannon", "砲塔火砲"),
    ("Lightning Damage", "雷電傷害"),
    ("Spell Recipe", "法術配方"),
    ("Holy Hand Grenade", "神聖手榴彈"),
    ("Flying Cow", "飛天牛"),
    ("Cooking Fat", "食用油脂"),
    ("New Game Plus", "新遊戲+"),
    ("Common Titan Rune", "普通泰坦符文"),
    ("Common", "普通"),
    ("Uncommon", "罕見"),
    ("Natural", "自然"),
    ("Dark", "黑暗"),
    ("Builder", "建築機"),
    ("Baby", "幼年"),
    ("Abyssal", "深淵"),
    ("Compressor", "壓縮機"),
    ("Inventory", "物品欄"),
    ("Egg", "蛋"),
    ("Drain", "汲取口"),
    ("Neutral", "中性"),
    ("Light", "光明"),
    ("Powered", "動力型"),
    ("Lucky", "幸運"),
    ("Owl", "貓頭鷹"),
    ("Military", "軍事"),
    ("Spell", "法術"),
    ("Bank", "儲存庫"),
    ("Pouch", "袋子"),
    ("Turd", "糞便"),
    ("Scout", "斥候"),
    ("Nut", "堅果"),
    ("Fireflash", "火閃"),
    ("Reinforced", "強化"),
    ("Counter", "流理臺"),
    ("Nullifier", "虛空器"),
    ("Slag", "爐渣"),
    ("Juicer", "榨汁機"),
    ("Module", "模組"),
    ("Enriched", "強化"),
    ("Lilypad", "荷葉"),
    ("Shulker", "界伏蚌"),
    ("Cleaver", "劈刀"),
    ("Mining", "採礦"),
    ("Lance", "長槍"),
    ("Napalm", "凝固汽油"),
    ("Bottle", "瓶子"),
    ("Taking Flight", "飛上天際"),
    ("Tesseract", "超立方體"),
    ("Vacuum", "真空"),
    ("Vector", "向量"),
    ("Binding", "束縛"),
    ("Bound", "束縛"),
    ("Displacement", "位移"),
    ("Prosperity", "富饒"),
    ("Roguelike", "類 Rogue"),
    ("Excavation", "挖掘"),
    ("Fire", "火焰"),
    ("Parchment", "羊皮紙"),
    ("Witchwood", "巫木"),
    ("Glass", "玻璃"),
    ("Housing", "外殼"),
    ("Port", "連接埠"),
    ("Trades", "交易"),
    ("Valve", "閥門"),
    ("Pearl", "珍珠"),
    ("Tracker", "追蹤器"),
    ("Entity", "實體"),
    ("Engine", "引擎"),
    ("Ignition", "點火器"),
    ("Balloon", "氣球"),
    ("Chassis", "底盤"),
    ("Energizer", "充能器"),
    ("Water Essence", "水之精華"),
    ("Water 精華", "水之精華"),
    ("Rocket 燃料", "火箭燃料"),
    ("Fishing Pond Builder", "釣魚池建造器"),
    ("Fishing Pond 建築機", "釣魚池建造器"),
    ("Experience Stuff(er)", "經驗儲存器"),
    ("Stuff(er)", "經驗儲存器"),
    ("Dragon Mounts", "騎乘龍"),
    ("Ice and Fire", "冰與火"),
    ("Punch", "衝擊"),
    ("Wing MKII", "MKII 機翼"),
    ("Wing MKI", "MKI 機翼"),
    ("Kit MKII", "MKII 套件"),
    ("Kit MKI", "MKI 套件"),
    ("Slice n' Splice", "切片接合機"),
    ("Rotor Blade", "轉子葉片"),
    ("Enticing Crystal", "誘引水晶"),
    ("Spider Eye", "蜘蛛眼"),
    ("Reborn Storage", "重生儲存"),
    ("Lily Pad of Fertility", "豐饒睡蓮"),
    ("Silk Touch", "絲綢之觸"),
    ("Laser Focus", "雷射聚焦透鏡"),
    ("Fortune Quarry", "幸運採石場"),
    ("Shrine of Knowledge", "知識神殿"),
    ("Draconic Weapon", "龍族武器"),
    ("EnderIO Enchanter", "EnderIO 附魔器"),
    ("Lightning Barrier", "雷電屏障"),
    ("Typhoon Wind", "颱風之風"),
    ("Plant Acceleration", "植物加速"),
    ("Stuff Repairing", "物品修復"),
    ("Fall Damage Immune", "免疫墜落傷害"),
    ("Water Breathing", "水下呼吸"),
    ("Health Regeneration", "生命回復"),
    ("Night Vision", "夜視"),
    ("Void Damage", "虛空傷害"),
    ("Extreme Hills", "極端山丘"),
    ("Spike Plains", "尖刺平原"),
    ("Ju' Li Sioux Reincarnation", "Ju' Li Sioux 轉生"),
    ("Reincarnation Catalyst", "轉生催化劑"),
    ("Extended Magazine", "擴容彈匣"),
    ("Amplifier Electron Tube", "放大電子管"),
    ("Training Dummy", "訓練假人"),
    ("Preheater Tower", "預熱塔"),
    ("Mass Fabrication", "物質製造"),
    ("Passively Cooled", "被動冷卻"),
    ("Breeding Pen", "繁殖圍欄"),
    ("Tool Rack", "工具架"),
    ("Gym GUI", "健身房 GUI"),
    ("Solar Panels", "太陽能板"),
    ("Canner", "裝罐機"),
    ("Coolant", "冷卻液"),
    ("Smelter", "冶煉爐"),
    ("Logic", "邏輯"),
    ("Sub Gift", "訂閱贈禮"),
    ("Florb", "流體球"),
    ("Quarry", "採石場"),
    ("Spider", "蜘蛛"),
    ("Fertilized", "肥沃"),
    ("Placer", "放置機"),
    ("Soul", "靈魂"),
    ("Skull", "頭顱"),
    ("Reliquary", "聖遺物"),
    ("Compound", "化合物"),
    ("Improved", "改良"),
    ("Cobalt", "鈷"),
    ("Fortune", "幸運"),
    ("Vibrant", "脈動"),
    ("Soularium", "靈魂合金"),
    ("Farm", "農場"),
    ("Stray", "流髑"),
    ("Bedrock", "基岩"),
    ("Turret", "砲塔"),
    ("Base", "基座"),
    ("Baconator", "培根供應器"),
    ("HarvestCraft", "豐收工藝"),
    ("Coke", "焦煤"),
    ("Dog", "狗"),
    ("Rat", "老鼠"),
    ("Compendium", "大全"),
    ("Bookshelf", "書櫃"),
    ("Lectern", "講台"),
    ("Arcane", "奧術"),
    ("Cake", "蛋糕"),
    ("Inlay", "鑲嵌"),
    ("Magmatic", "岩漿"),
    ("Potion", "藥水"),
    ("Plastic", "塑膠"),
    ("Tree", "樹"),
    ("Pig", "豬"),
    ("Cow", "牛"),
    ("Sheep", "羊"),
    ("Fence", "柵欄"),
    ("Breeder", "繁殖機"),
    ("Chronotyper", "年齡分類機"),
    ("Resistance II", "抗性提升 II"),
    ("High Step", "跨步提升"),
    ("Speed", "速度"),
    ("Jump", "跳躍提升"),
    ("Flying", "飛行"),
    ("Invisibility", "隱形"),
    ("Haste", "挖掘加速"),
    ("Necklace", "項鍊"),
    ("Plain", "平原"),
    ("Desert", "沙漠"),
    ("Stage", "階段"),
    ("Rabbit", "兔子"),
    ("Plains", "平原"),
    ("Den", "巢穴"),
    ("Collection", "收集"),
    ("Nugget", "粒"),
    ("Piercing", "穿透"),
    ("Dig", "挖掘"),
    ("Tome", "典籍"),
    ("Stuff", "物品"),
    ("Paper", "紙"),
    ("Great", "偉大"),
    ("Spawn", "生成"),
    ("Spirit", "靈魂"),
    ("Catalyst", "催化劑"),
    ("Artifact", "遺物"),
    ("Council", "議會"),
    ("Portal", "傳送門"),
    ("Reincarnation", "轉生"),
    ("Fleet", "艦隊"),
    ("Kingdom", "王國"),
    ("Launch", "發射"),
    ("Slow Fall", "緩降"),
    ("Trap", "陷阱"),
    ("Pioneer", "開拓者"),
    ("Overworld", "主世界"),
    ("Uranium", "鈾"),
    ("Forge Lexicon", "鍛造辭典"),
    ("Shader", "塗裝"),
    ("Training", "訓練"),
    ("Bayonet", "刺刀"),
    ("Blueprint", "藍圖"),
    ("Shotgun", "散彈槍"),
    ("Crystallized", "結晶"),
    ("Onyx", "縞瑪瑙"),
    ("Aerbunny", "飛天兔"),
    ("Immune", "免疫"),
    ("Ocean", "海洋"),
    ("The Fallen", "墮落者"),
    ("Chagaroth Fist", "Chagaroth 之拳"),
    ("Shears", "剪刀"),
    ("Bowl", "碗"),
    ("Mooshroom", "蘑菇牛"),
    ("Bus", "匯流排"),
    ("Connector", "連接器"),
    ("Generating Power", "發電"),
    ("Gravel", "礫石"),
    ("Grass", "草方塊"),
    ("Sandstone", "砂岩"),
    ("Brick", "磚塊"),
    ("Netherrack", "地獄石"),
    ("Ranged Pumps", "遠端幫浦"),
    ("Canister", "罐"),
    ("Ars Kicking Magica", "Ars Magica 大顯神威"),
    ("Magic", "魔法"),
    ("Lightning", "閃電"),
    ("Tofu", "豆腐"),
    ("Grout", "填縫泥"),
    ("Anvil", "鐵砧"),
    ("Manyullyn", "瑪玉靈"),
    ("Crystal", "水晶"),
    ("Ardite", "阿迪特"),
    ("Card", "卡片"),
    ("Fireblast", "火焰衝擊"),
    ("Drawer", "抽屜"),
    ("Pet", "寵物"),
    ("Pendant", "墜飾"),
    ("Station", "工作站"),
    ("Fabricator", "製造機"),
    ("Random Things", "隨機物品"),
    ("Ultra Rare", "超稀有"),
    ("Levels", "等級"),
    ("Irish", "愛爾蘭"),
    ("UI", "介面"),
    ("Old Spice", "Old Spice"),
    ("Regenerating", "回復"),
    ("End", "終界"),
    ("Wall", "牆"),
    ("Utilities", "工具"),
    ("Mystical", "神秘"),
    ("Ars Kicking Magicka", "Ars Magicka 大顯神威"),
    ("Magelight", "魔光"),
    ("Object Submission Station", "物件繳交站"),
    ("Object Submission", "物件繳交"),
    ("EnderIO Enchanter", "EnderIO 附魔器"),
    ("Enchanter", "附魔器"),
    ("Asorah's", "Asorah 的"),
    ("Tinkers'", "匠魂"),
    ("Matter", "物質"),
    ("Splash", "飛濺型"),
    ("Wing", "機翼"),
    ("TOWER", "高塔"),
    ("Ultra", "超稀有"),
    ("Gym", "健身房"),
    ("Justice", "正義"),
    ("Big", "大型"),
    ("Can", "罐"),
    ("Large Bloodstone Brick", "大型血石磚"),
    ("Large Bloodstone", "大型血石"),
    ("Damage", "傷害"),
)


TEXT_CLEANUPS = (
    ("Alkahestry 典籍", "萬能溶劑之經"),
    ("黑暗夜黑之耳", "夜黑之耳"),
    ("Kappa 鎬", "Kappa鎬"),
    ("鎆", "鎦"),
    ("Wiki", "維基"),
    ("《《血魔法血之祭壇指南》》", "《血魔法血之祭壇指南》"),
    ("液態以太液", "液態以太"),
    ("Gaia 魔物書", "蓋亞魔典"),
    ("Ethetic 石英", "裝飾用石英方塊"),
    ("過載值", "耗竭值"),
    ("末影龍", "終界龍"),
    ("附魔臺", "附魔台"),
    ("合成臺", "合成台"),
    ("基巖", "基岩"),
    ("巖", "岩"),
    ("拆解台（拆解臺）", "拆解台"),
    ("發電發電機", "發電機"),
    ("實體實體偵測器", "實體偵測器"),
    ("烹飪傻瓜書食譜書", "烹飪傻瓜書"),
    ("Doomlike 地牢", "類《Doom》地牢"),
    ("Doom Like 地牢", "類《Doom》地牢"),
    ("類 Rogue 地牢", "類《Rogue》地牢"),
    ("Da§crk", "黑§c暗"),
    ("Elemental 泰坦", "元素泰坦"),
    ("AbyssalCraft Wiki", "AbyssalCraft 維基"),
    ("合成合成種子來合成種子", "用合成種子合成種子"),
    ("超頻升級升級", "超頻升級"),
    ("種子種子再處理器", "種子再處理器"),
    ("束縛束縛之刃", "束縛之刃"),
    ("製作建造第 4 階祭壇", "建造第 4 階祭壇"),
    ("靈魂靈魂網路", "靈魂網路"),
    ("奧術奧術灰燼", "奧術灰燼"),
    ("閃電閃電箭", "閃電箭"),
    ("物件繳交站（OSS，物件繳交站）", "物件繳交站（OSS）"),
    ("裝備終界採石場的殺手喬", "裝備終界之劍的殺手喬"),
    ("查看 Wiki", "查看維基"),
    ("守護者護甲（守衛者護甲）", "守護者護甲"),
    ("海底神殿（水中神殿）", "海底神殿"),
    ("祛魔台（祛魔臺）", "祛魔台"),
    ("進階高爐（高等高爐）", "高等高爐"),
    ("能量發射器（能量輸出器）", "能量發射器"),
    ("焦爐（焦煤爐）", "焦煤爐"),
    ("烹飪台（烹飪桌）", "烹飪台"),
    ("釣魚池建築機（釣魚池建造器）", "釣魚池建造器"),
    ("核能反應爐（核反應爐）", "核反應爐"),
    ("幼年過濾器（幼體過濾器）", "幼年過濾器"),
    ("吸收盾牌（吸收護盾）", "吸收護盾"),
    ("書 of 吸收（吸收之書）", "吸收之書"),
    ("煉金法陣（鍊金法陣）", "煉金法陣"),
    ("束縛劍（束縛之劍）", "束縛之劍"),
    ("Blood 碎片（血之碎片）", "血之碎片"),
    ("儀式石頭（儀式石）", "儀式石"),
    ("Master 血之寶珠", "大師血之寶珠"),
    ("大師血之寶珠（大師血之寶珠）", "大師血之寶珠"),
    ("儀式占卜器（儀式預言杖）", "儀式占卜杖"),
    ("耗竭值（過載）", "耗竭值"),
    ("銘文台（書寫台）", "銘文台"),
    ("構件（組成要素）", "構件"),
    ("合成祭壇（法術祭壇）", "合成祭壇"),
    ("高等發電機（進階發電機）", "高等發電機"),
    ("深淵荒原（深淵荒地）", "深淵荒原"),
    ("血月地堡（血月碉堡）", "血月地堡"),
    ("每日補給包（日常補給包）", "每日補給包"),
    ("一個形態（投射物）與一個構件（雷電傷害）", "一個「投射物」形態與一個「雷電傷害」構件"),
    ("感應器 (階級 1)", "1 階感應器"),
    ("感應器（階級 1）", "1 階感應器"),
    ("龍 Mounts", "騎乘龍"),
    ("冰 and 火焰", "冰與火"),
    ("《Clash of the 泰坦》", "《泰坦之戰》"),
    ("Object Submission 工作站", "物件繳交站"),
    ("§墜塔印記", "§d墜塔印記"),
    ("am2.wika.com/wiki/Bosses。", "am2.wika.com/wiki/Bosses 。"),
    ("aam2.wikia.com/wiki/Spells_and_other_help§6", "aam2.wikia.com/wiki/Spells_and_other_help §6"),
    ("「幼年」過濾器（幼體過濾器）", "「幼年」過濾器"),
    ("傷害陷阱（傷害陷阱）", "傷害陷阱"),
    ("大型血石磚塊（大型血石磚）", "大型血石磚"),
    ("大師血之寶珠§6§f（大師血之寶珠）", "大師血之寶珠§6§f"),
    ("銘文台（書寫臺）", "銘文台"),
    ("流體輸入口閥門（流體輸入閥）", "流體輸入閥"),
    ("物件繳交工作站（OSS，物件繳交站）", "物件繳交站（OSS）"),
)


URL_PATTERN = re.compile(
    r"(?:https?://|www\.)\S+|"
    r"(?:[A-Za-z0-9-]+\.)+(?:com|net|org|io|wiki)(?:/\S*)?",
    re.IGNORECASE,
)
FORMAT_PATTERN = re.compile(r"§[0-9A-FK-ORa-fk-or]")
CJK_PATTERN = re.compile(r"[\u3400-\u9fff]")
ENGLISH_CHINESE_GLOSS_PATTERN = re.compile(
    r"(?<![A-Za-z0-9])"
    r"[A-Za-z][A-Za-z0-9'’/+.-]*(?:[ \t]+[A-Za-z0-9][A-Za-z0-9'’/+.-]*)*"
    r"[（(]([^）)\n]*[\u3400-\u9fff][^）)\n]*)[）)]"
)


def _whole_term_pattern(term: str) -> re.Pattern[str]:
    prefix = r"(?<![A-Za-z0-9])" if term[0].isalnum() else ""
    suffix = r"(?![A-Za-z0-9])" if term[-1].isalnum() else ""
    return re.compile(prefix + re.escape(term) + suffix, re.IGNORECASE)


PROTECTED_PATTERNS = tuple(
    (_whole_term_pattern(term), term)
    for term in sorted(PROTECTED_TERMS, key=len, reverse=True)
)
REPLACEMENT_PATTERNS = tuple(
    (_whole_term_pattern(source), target)
    for source, target in sorted(TERM_REPLACEMENTS, key=lambda item: len(item[0]), reverse=True)
)
EXACT_REPLACEMENTS = {source.casefold(): target for source, target in TERM_REPLACEMENTS}
EXACT_TITLE_TRANSLATIONS = {
    source.casefold(): target for source, target in TITLE_TRANSLATIONS.items()
}


def polish_quest_terminology(text: str) -> str:
    """Translate clear game terms without touching links or protected IDs."""
    stripped = text.strip()
    exact_title = EXACT_TITLE_TRANSLATIONS.get(stripped.casefold())
    if exact_title is not None:
        return exact_title
    exact = EXACT_REPLACEMENTS.get(stripped.casefold())
    if exact is not None and stripped == text:
        return exact

    # Pure-English quest titles commonly depend on puns.  Only exact glossary
    # entries above are safe to translate without destroying the joke.
    if not CJK_PATTERN.search(text):
        return text

    protected: list[str] = []

    def hold(value: str) -> str:
        index = len(protected)
        protected.append(value)
        return f"\ue000{index}\ue001"

    result = URL_PATTERN.sub(lambda match: hold(match.group(0)), text)
    result = FORMAT_PATTERN.sub(lambda match: hold(match.group(0)), result)
    for pattern, _term in PROTECTED_PATTERNS:
        result = pattern.sub(lambda match: hold(match.group(0)), result)
    for pattern, replacement in REPLACEMENT_PATTERNS:
        result = pattern.sub(replacement, result)
    for source, replacement in TEXT_CLEANUPS:
        result = result.replace(source, replacement)

    # Bilingual glosses are removed through explicit cleanup rules above.
    # A generic regex is unsafe here because coordinates and abbreviations such
    # as Y60（島嶼高度） or IC2（其他模組物品）carry real information.
    for replacement in set(EXACT_REPLACEMENTS.values()):
        result = result.replace(f"{replacement}（{replacement}）", replacement)
        result = result.replace(f"{replacement} ({replacement})", replacement)
    result = re.sub(
        r"([\u3400-\u9fff]{2,24})（\1）",
        r"\1",
        result,
    )

    for index, value in enumerate(protected):
        result = result.replace(f"\ue000{index}\ue001", value)
    for source, replacement in TEXT_CLEANUPS:
        result = result.replace(source, replacement)
    return re.sub(r"(?<=[\u3400-\u9fff])[ \t]+(?=[\u3400-\u9fff])", "", result)


def polish_quest_translation(source: str, target: str) -> str:
    """Apply source-specific review decisions, then the shared terminology pass."""
    title_correction = EXACT_TITLE_TRANSLATIONS.get(source.strip().casefold())
    if title_correction is not None:
        return polish_quest_terminology(title_correction)
    exact_correction = SOURCE_EXACT_CORRECTIONS.get(source)
    if exact_correction is not None:
        return polish_quest_terminology(exact_correction)
    for marker, correction in SOURCE_STARTS_CORRECTIONS:
        if source.startswith(marker):
            return polish_quest_terminology(correction)
    for marker, correction in SOURCE_CONTAINS_CORRECTIONS:
        if marker in source:
            target = correction
            break
    return polish_quest_terminology(target)
